import "~/styles/globals.css";

import { Inter } from "next/font/google";
import Link from "next/link";
import { ArchiveBoxArrowDownIcon } from "@heroicons/react/24/outline";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = true;

  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <div className="container mx-auto">
          <div className="flex justify-between py-12">
            <p className="text-2xl">Bookify Store</p>

            <nav>
              <Link href={"/"} className="px-5">
                Home
              </Link>
              <Link href={"/shop"} className="px-10">
                Shop
              </Link>
              <Link
                href={session ? "/api/auth/signout" : "/api/auth/signin"}
                className="rounded-xl bg-black px-5 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
              >
                {session ? "Sign out" : "Sign in"}
              </Link>
            </nav>
          </div>
        </div>

        {children}

        <div className="bg-black">
          <div className="container mx-auto flex justify-between py-12 text-white">
            <p>Bookify Store</p>
            <p>2024 Bookify Store. All rigth are reserved.</p>
            <div className="flex">
              <ArchiveBoxArrowDownIcon className="mx-4 w-8" />
              <ArchiveBoxArrowDownIcon className="mx-4 w-8" />
              <ArchiveBoxArrowDownIcon className="mx-4 w-8" />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
